"""
Copyright (C) 2018  Heriberto J. Díaz Luis-Ravelo

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""


ackCommand = '@'
acquisitionCommand = '&'
experimentCommand = '|'
messageNecessaryLaserON = 'It is necessary the laser is switch ON.'
messageNecessaryPeristalticON = 'It is necessary the peristaltic is switch ON.'
messageChangeExperimentTimePart1 = 'Remember, the time experiment is limited to '
messageChangeExperimentTimePart2 = ' s. Do you want to change this value?'
messageSaveData = 'Do you want to save the data?'
messageLoadConfigurationFile = 'Load a configuration file?'
messageExit = 'Are you sure you want to quit?'
messagePortNotOpen = 'Port cannot be opened'
messagePortNotFound = 'Port do not found, please choose an available port.'
messageTimeoutLaser = 'The laser was not switch ON/OFF, try again.'
messageTimeoutPeristaltic = 'The peristaltic did not respond, try again.'
messageTimeoutImpulsionalA = 'The impulsional A pump did not respond, try again.'
messageTimeoutImpulsionalB = 'The impulsional B pump did not respond, try again.'
messageTimeoutCalibrate = 'The device has not been calibrated, try again.'
messageTimeoutAutomatic = 'The device has not respond, try again.'
messageTimeoutInitExperiment = 'The device has not respond, try again.'
messageNotCeroImpulsionalA = 'The value of the impulsional A cannot be 0.'
messageNotCeroImpulsionalB = 'The value of the impulsional B cannot be 0.'
write = 'w'
portCOM = 'COM1'
connect = 'Connect'
disconnect = 'Disconnect'
portConnected = 'Port Connected'
angle = 'ANGLE'
timeUC = 'TIME'
timeLC = 'Time'
channel1UC = 'CHANNEL 1'
channel1LC = 'Channel 1'
channel1dots = 'Channel 1:'
channel2UC = 'CHANNEL 2'
channel2LC = 'Channel 2'
channel2dots = 'Channel 2:'
no = 'No'
start = 'START'
stop = 'STOP'
reset = 'Reset'
forwardLC = 'forward'
forwardUC = 'FORWARD'
backLC = 'back'
backUC = 'BACK'
exitLC = 'Exit'
automatic = 'Automatic'
error = 'Error'
result = 'Result'
question = 'Question'
openFile = 'Open File'
saveFileLC = 'Save File'
saveFileUC = 'SAVE FILE'
inject = 'INJECT'
purge = 'PURGE'
laserON = 'Laser ON'
laserOFF = 'Laser OFF'
laserStart = 'Start Laser'
laserStop = 'Stop Laser'
laserControl = 'Laser Control'
pumpsControl = 'Pumps Control'
flowPeristaltic = 'Flow Peristaltic'
peristalticPumpControl = 'Peristaltic Pump Control'
injectionImpulsionalA = 'Injection Impulsional A:'
injectionA = 'Injection A:'
impulsionalPumpAControl = 'Impulsional Pump A Control'
impulsionalPumpBControl = 'Impulsional Pump B Control'
injectionImpulsionalB = 'Injection Impulsional B:'
injectionB = 'Injection B:'
gainA = 'Gain A:'
gainB = 'Gain B:'
offsetA = 'Offset A:'
offsetB = 'Offset B:'
calibrate = 'Calibrate'
initialAngle = 'Initial Angle:'
angleLongitude = 'Angle Longitude:'
angleResolution = 'Angle Resolution:'
finalAngle = 'Final Angle:'
pointsOfCurve = 'Points of Curve:'
dataSamplingSeconds = 'Data Sampling (seconds):'
dataSampling = 'Data Sampling:'
calibrationParameters = 'Calibration Parameters'
curvePerformance = 'Curve Performance'
acquisitionMode = 'Acquisition Mode'
angleOfIncidence = 'Angle of Incidence'
signalAmplitude = 'Signal Amplitude'
experimentTime = 'Experiment Time:'
startExperiment = 'Start Experiment'
stopExperiment = 'Stop Experiment'
timeParameters = 'Time Parameters'
fluidicParameters = 'Fluidic Parameters'
statusLaser = 'Status Laser'
freeRunning = 'Free Running'
x1000 = 'x1000'
x10000 = 'x10000'
autoscaleX = 'Autoscale X'
autoscaleY = 'Autoscale Y'
injectionPumpControl = 'Injection Pump Control'
systemControl = 'System Control'
sprCurveSetup = 'SPR Curve Setup'
dataAcquisition = 'Data Acquisition'
portsUC = 'PORTS'
imageLogoFull = 'image/Nanob2a_Logo_Full.png'
imageLogoHalf = 'image/Nanob2a_Logo_Half.png'
imageSPRDevice = 'image/SPR_Device_v2.png'
imageSPRFrontGreen = 'image/SPR_Front_Green.png'
imageSPRFrontRed = 'image/SPR_Front_Red.png'
otherLayout = 'Other Layout'
sprV2 = 'SPR V2'
formatEnglish = 'English'
unitTime = ' s'
intensity = 'Intensity'
derivative = 'Derivative'
